server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: localSecretKeyForDevelopment
  expiration: 86400000

logging:
  level:
    com.nexus.user: DEBUG
    org.springframework.security: DEBUG
