server:
  port: 8081

spring:
  spring:
    config:
      import: optional:configserver:http://localhost:8888
      spring:
        application:
          name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: localSecretKeyForDevelopment
  expiration: 86400000

logging:
  level:
    com.nexus.user: DEBUG
    org.springframework.security: DEBUG
eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
