server:
  port: 8085

spring:
  config:
      import: optional:configserver:http://localhost:8888
  application:
    name: notification-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
