apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: nexus-ai-logs-*
    isDefault: true
    jsonData:
      timeField: "@timestamp"
